### ISSUE TITLE
Date type conversion changes the timezone of MySQL datetime. How to disable?

### ISSUE THREAD

**Issue by webdev3301** [jeremiah-shaulov/office_spirit_mysql#1]
Hello. Your library is not just converting MySQL datetime to Javascript. It is also converting it to UTC. If datetime is store in any other time zone, the library corrupts all datetimes. Please tell me there's a way to turn this off.

My MySQL database stores dates in Mountain Standard Time.
I send 2 dates as a range to MySQL in Mountain Standard Time.
The library adds 6 HOURS TO EACH and then sends the query?

**Comment by webdev3301** [comment]
Alright. I was able to use `.toLocaleString("en-US", {timeZone: "America/Denver"})`

**Comment by jeremiah-shaulov** [comment]
Hi. Sorry for late reply. If still relevant, try office_spirit_mysql@v0.11.0

If you specify `datesAsString` parameter in connection string, dates will be returned as strings.

Also read about [timezone conversion](https://github.com/jeremiah-shaulov/office_spirit_mysql#timezone)
